# Generated by Django 4.2.10 on 2024-04-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_group_home_group_icon'),
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo'),
        ),
    ]
