# Generated by Django 4.2.10 on 2024-04-20 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Reparticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Programa')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Monto')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Modificacion')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prensa.medio', verbose_name='Medio')),
                ('reparticion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prensa.reparticion', verbose_name='Reparticion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
