# Generated by Django 4.2.10 on 2024-04-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
