# Generated by Django 4.2.10 on 2024-04-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0003_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'AUTORIZADO'), ('D', 'DENEGADO')], default='P', max_length=10),
        ),
    ]
