# Generated by Django 4.2.10 on 2024-04-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0004_contrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'AUTORIZADO'), ('D', 'DENEGADO')], default='P', max_length=10, verbose_name='Estado'),
        ),
    ]
