# Generated by Django 4.2.10 on 2024-04-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0005_alter_contrato_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'permissions': (('admin_prensa', 'Admin  de Prensa'),), 'verbose_name': 'Prensa', 'verbose_name_plural': 'Prensa'},
        ),
    ]
