# Generated by Django 4.2.10 on 2024-04-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0007_contrato_proveedor_rs_contrato_proveeodr_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='proveeodr_cuit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Programa'),
        ),
    ]
