# Generated by Django 4.2.10 on 2024-04-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0008_alter_contrato_proveeodr_cuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='proveeodr_cuit',
            new_name='proveedor_cuit',
        ),
    ]
