# Generated by Django 4.2.10 on 2024-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_profile_apellidoresponsable_profile_caracter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='caracter',
            field=models.CharField(choices=[('T', 'TITULAR'), ('R', 'RESPONSABLE')], max_length=10),
        ),
    ]
