# Generated by Django 4.2.10 on 2024-03-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_profile_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telefono',
            new_name='tel',
        ),
    ]
