# Generated by Django 4.2.10 on 2024-03-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_rename_telefono_profile_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tel',
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
