# Generated by Django 4.2.10 on 2024-03-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_profile_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menugrupo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
