# Generated by Django 4.2.10 on 2024-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_menugrupo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
