# Generated by Django 4.2.10 on 2024-04-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_profile_disabled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
