# Generated by Django 4.2.10 on 2024-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_profile_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
