"""
Django settings for siaf project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xlc9ygf7mpji)x!b1q$=b=20rj3!=^zlx+(nc_d+1rq+8s^wm_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



USE_L10N = True
LANGUAGE_CODE = 'es-es'

ALLOWED_HOSTS = ['*']
# Configuracion de correo

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp-mail.outlook.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tesoreria@jujuy.gob.ar'
# EMAIL_HOST_PASSWORD = 'Kuqu1104'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "sistema",
    "proveedores",
    "administrador",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'sistema.middleware.NotFoundMiddleware'
]

ROOT_URLCONF = 'siaf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'siaf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

env = environ.Env(
    DATABASE_DATA_NAME=(str, ""),
    DATABASE_DATA_USER=(str, ""),
    DATABASE_DATA_PASS=(str, ""),
    DATABASE_DATA_HOST=(str, ""),
    DATABASE_DATA_PORT=(str, ""),
)

environ.Env.read_env("/var/www/envvar/configparameters_siaf")


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env('DATABASE_DATA_NAME'),
        "USER": env('DATABASE_DATA_USER'),
        "PASSWORD": env('DATABASE_DATA_PASS'),
        "HOST": env('DATABASE_DATA_HOST'),
        "PORT": env('DATABASE_DATA_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-AR'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    BASE_DIR / 'static/',
)
STATIC_ROOT = '/var/www/static-siaf/'

MEDIA_ROOT = '/var/www/media-siaf/'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

import os

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = "smtp.office365.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "tesoreria@jujuy.gob.ar"
SERVER_EMAIL = "tesoreria@jujuy.gob.ar"
DEFAULT_FROM_EMAIL = "tesoreria@jujuy.gob.ar"
EMAIL_HOST_PASSWORD = "XVaaQ1342!asdf!?"
EMAIL_USE_TLS = True
