# Generated by Django 5.0.2 on 2024-02-21 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razon Social')),
                ('cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT')),
            ],
        ),
        migrations.CreateModel(
            name='CPOPAGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpopanio', models.IntegerField(blank=True, null=True, verbose_name='Ejercicio del Pago')),
                ('cpopnro', models.IntegerField(blank=True, null=True, verbose_name='Nro. de Pago')),
                ('copaanio', models.IntegerField(blank=True, null=True, verbose_name='Ejercicio de la Ord. de Pago')),
                ('cjurcod', models.CharField(blank=True, max_length=1, null=True, verbose_name='Jurisdiccion')),
                ('crepudo', models.CharField(blank=True, max_length=4, null=True, verbose_name='UDO (Unidad de Organización)')),
                ('copanro', models.IntegerField(blank=True, null=True, verbose_name='Nro. de Ord. De Pago')),
                ('cbencui', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUIT')),
                ('cpoptip', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo de Pago')),
                ('cchqnum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nro. de Cheque')),
                ('cchqcta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nro de Cuenta')),
                ('cchqtip', models.CharField(blank=True, max_length=4, null=True, verbose_name='Tipo de Cheque')),
                ('cpopimp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe')),
                ('cpopfpg', models.DateTimeField(blank=True, null=True, verbose_name='Fec. De Pago')),
                ('corbanio', models.IntegerField(blank=True, null=True, verbose_name='Ejer. Orden bancaria')),
                ('corbnro', models.IntegerField(blank=True, null=True, verbose_name='Nro Orden Bancaria')),
                ('cndbanio', models.IntegerField(blank=True, null=True, verbose_name='Ejer. Nota de Debito')),
                ('cndbnro', models.IntegerField(blank=True, null=True, verbose_name='Nro. Nota de Debito')),
                ('cpop096', models.CharField(blank=True, max_length=10, null=True, verbose_name='Usuario Alta')),
                ('cpop097', models.DateTimeField(blank=True, null=True, verbose_name='Fec.Alta')),
                ('cpop098', models.CharField(blank=True, max_length=10, null=True, verbose_name='Usuario Modif')),
                ('cpop099', models.DateTimeField(blank=True, null=True, verbose_name='Fec.Modif')),
                ('cpopest', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado del Pago')),
                ('cpopjur', models.CharField(blank=True, max_length=1, null=True, verbose_name='Jur Origen del Pago')),
                ('cpopudo', models.CharField(blank=True, max_length=4, null=True, verbose_name='UDO origen del Pago')),
                ('cpophab', models.CharField(blank=True, max_length=1, null=True, verbose_name='Habilitacion')),
                ('copapgd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pagado')),
                ('copasdo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo')),
                ('cchqfpg', models.DateTimeField(blank=True, null=True, verbose_name='Fec.Entrega Cheque')),
                ('cchq097', models.DateTimeField(blank=True, null=True, verbose_name='Fec.Ingreso Mes.Entrada')),
                ('cchqest', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado Cheq')),
                ('cchqant', models.CharField(blank=True, max_length=1, null=True, verbose_name='Anticipo Cheque')),
                ('cchqtic', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo de cheque')),
                ('copafue', models.IntegerField(blank=True, null=True, verbose_name='Fuente OP')),
                ('cchqben', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Beneficiario del Cheque')),
                ('cla2suc', models.IntegerField(blank=True, null=True, verbose_name='Sucursal Banco')),
                ('cla2cta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro.Cta Acred.Banco')),
                ('cla2imp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe Acreditado')),
                ('ctippag', models.CharField(blank=True, max_length=1, null=True, verbose_name='Pago Bancarizado')),
                ('copaest', models.IntegerField(blank=True, null=True, verbose_name='Estado OP')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
