# Generated by Django 5.0.2 on 2024-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpopago',
            name='cbencui',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='CUIT'),
        ),
    ]
